name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Dispara el flujo cuando se crea un tag que comience con "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/acceso-datos-docker:${{ env.VERSION }} . && docker push ${{ secrets.DOCKERHUB_USERNAME }}/acceso-datos-docker:${{ env.VERSION }}

